######################################################################
# Automatically generated by qmake (3.0) Tue Jan 19 17:11:22 2016
######################################################################

CONFIG += debug

QT += widgets

TEMPLATE = app
TARGET = ogdf
INCLUDEPATH += .

# Input
FORMS += mainWindow.ui
HEADERS += mainWindow.h graphView.h
SOURCES += main.cpp mainWindow.cpp graphView.cpp

LIBS += -lOGDF
